RID_COLUMN = 0
TIMESTAMP_COLUMN = 1
SCHEMA_ENCODING_COLUMN = 2
INDIRECTION_COLUMN = 3
BASE_ID = 4

PAGE_CAPACITY = 4096  
DATA_ENTRY_SIZE = 8  
MAX_PAGES_PER_RANGE = 16  
TUPLE_SIZE = 8  
TUPLES_PER_PAGE = PAGE_CAPACITY // TUPLE_SIZE  
TUPLES_PER_PAGERANGE = MAX_PAGES_PER_RANGE * TUPLES_PER_PAGE 
DEFAULT_PAGE_COUNT = 5  
MAX_64BIT_INT = 2**64 - 1  
BUFFERPOOL_MAX_LENGTH = 1000
